---
title: "CPM"
author: "Siwei Zeng"
date: "2020/2/27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(LANG = "en")
library(stringr)
```

```{r Load dataset}
rm(list = ls())

fileName <- "activities.csv"

# Read .csv file and rename the columns
reloadCsv <- function(fileName) {
  activities <- read.csv(file = fileName, header = TRUE, na.strings = "", blank.lines.skip = TRUE, stringsAsFactors = FALSE, fileEncoding = "UTF-8", encoding = "UTF-8")
  colnames(activities)<-c("Activities", "Immediate Predecessor Activities", "Optimistic Time", "Most Likely Time", "Pessimistic Time")
  return(activities)
}

activities <- reloadCsv(fileName)
```

```{r Default NA processing}
# Process NA of optimistic time, most likely time and pessimistic time
naParse3Single <- function(amb) {
  ambTemp <- amb
  naStatus <- ""
  if (is.na(ambTemp[1])) {
    naStatus <- paste0(naStatus, "1")
  } else {
    naStatus <- paste0(naStatus, "0")
  }
  if (is.na(ambTemp[2])) {
    naStatus <- paste0(naStatus, "1")
  } else {
    naStatus <- paste0(naStatus, "0")
  }
  if (is.na(ambTemp[3])) {
    naStatus <- paste0(naStatus, "1")
  } else {
    naStatus <- paste0(naStatus, "0")
  }
  if (naStatus == "111") {
    ambTemp[1:3] <- 0
  } else if (naStatus == "011") {
    ambTemp[c(2,3)] <- ambTemp[1]
  } else if (naStatus == "101") {
    ambTemp[c(1,3)] <- ambTemp[2]
  } else if (naStatus == "110") {
    ambTemp[c(1,2)] <- ambTemp[3]
  } else if (naStatus == "100") {
    ambTemp[1] <- 0
  } else if (naStatus == "010") {
    ambTemp[2] <- 0
  } else if (naStatus == "001") {
    ambTemp[3] <- 0
  } else if (naStatus == "000") {
  }
  return(ambTemp)
}

naParse3 <- function(ambMultiple) {
  ambMultipleTemp <- ambMultiple
  for (i in 1:dim(ambMultiple)[1]) {
    ambMultipleTemp[i,1:3] <- naParse3Single(ambMultiple[i,1:3])
  }
  return(ambMultipleTemp)
}

activities[,3:5] <- naParse3(activities[,3:5])
```

```{r Expected time calculation}
# Calculate expected time
calculateTE <- function(ambMultiple) {
  ambMultiple <- as.matrix(ambMultiple)
  returnTemp <- 1:dim(ambMultiple)[1]
  for (i in 1:dim(ambMultiple)[1]) {
    returnTemp[i] <- (ambMultiple[i,1] + 4 * ambMultiple[i,2] + ambMultiple[i,3]) / 6
  }
  return(returnTemp)
}

activities$`Expected Time` <- calculateTE(activities[,3:5])
```

```{r Variance calculation}
# Calculate variance
calculateVariance <- function(ambMultiple) {
  ambMultiple <- as.matrix(ambMultiple)
  returnTemp <- 1:dim(ambMultiple)[1]
  for (i in 1:dim(ambMultiple)[1]) {
    returnTemp[i] <- ((ambMultiple[i,3] - ambMultiple[i,1]) / 6)^2
  }
  return(returnTemp)
}

activities$Variance <- calculateVariance(activities[,3:5])
```

```{r Standard deviation calculation}
# Calculate standard deviation
calculateStandardDeviation <- function(ambMultiple) {
  ambMultiple <- as.matrix(ambMultiple)
  returnTemp <- 1:dim(ambMultiple)[1]
  for (i in 1:dim(ambMultiple)[1]) {
    returnTemp[i] <- (ambMultiple[i,3] - ambMultiple[i,1]) / 6
  }
  return(returnTemp)
}

activities$`Standard Deviation` <- calculateStandardDeviation(activities[,3:5])
```

```{r preList Generation}
# Generate preList
generatePreList <- function(ipa) {
  return(str_split(ipa, ","))
}

preList <- generatePreList(activities$`Immediate Predecessor Activities`)
```

```{r postList Generation, warning = FALSE}
# Generate postList
preList2PostList <- function(activities, preList) {
  postList <- preList
  for (i in 1:length(postList)) {
    postList[[i]] <- NA_character_
  }
  for (i in 1:length(preList)) {
    if (!is.na(preList[[i]])) {
      for (preNo in which(is.element(activities, preList[[i]]))){
        if (is.na(postList[[preNo]])) {
          postList[[preNo]] <- activities[i]
        } else {
          postList[[preNo]] <- c(postList[[preNo]], activities[i])
        }
      }
    }
  }
  return(postList)
}

postList <- preList2PostList(activities$Activities, preList)
```

```{r startNodes, endNodes generation}
# Generate startNodes
generateStartNodes <- function(activities, preList) {
  startNodes <- NA_character_
  for (i in 1:length(preList)) {
    if (is.na(preList[i])) {
      startNodes <- c(startNodes, activities[i])
    }
  }
  startNodes <- na.omit(startNodes)
}

startNodes <- generateStartNodes(activities$Activities, preList)

#Generate endNodes
generateEndNodes <- function(activities, postList) {
  endNodes <- NA_character_
  for (i in 1:length(postList)) {
    if (is.na(postList[i])) {
      endNodes <- c(endNodes, activities[i])
    }
  }
  endNodes <- na.omit(endNodes)
}

endNodes <- generateEndNodes(activities$Activities, postList)
```

```{r ES, EF calculation}
# Calculate ES, EF
calculateESEF <- function(activities, preList, expectedTime) {
  ES <- 1:length(activities)
  EF <- 1:length(activities)
  for (i in 1:length(ES)) {
    ES[i] <- NA_real_
  }
  for (i in 1:length(EF)) {
    EF[i] <- NA_real_
  }
  ES[which(is.na(preList))] <- 0
  EF[which(ES == 0)] <- ES[which(ES == 0)] + expectedTime[which(ES == 0)]
  while (any(is.na(ES))) {
    for (i in 1:length(activities)) {
      if (is.na(ES[i])) {
        preListNow <- preList[[i]]
        if (!any(is.na(EF[which(is.element(activities, preListNow))]))) {
          ES[i] <- max(EF[which(is.element(activities, preListNow))])
          EF[i] <- ES[i] + expectedTime[i]
        }
      }
    }
  }
  return(list(ES, EF))
}

activities$ES <- calculateESEF(activities$Activities, preList, activities$`Expected Time`)[[1]]
activities$EF <- calculateESEF(activities$Activities, preList, activities$`Expected Time`)[[2]]
```

```{r LS, LF calculation, warning = FALSE}
# Calculate LS, LF
calculateLSLF <- function(activities, postList, expectedTime, EF) {
  LS <- 1:length(activities)
  LF <- 1:length(activities)
  for (i in 1:length(LS)) {
    LS[i] <- NA_real_
  }
  for (i in 1:length(LF)) {
    LF[i] <- NA_real_
  }
  LF[which(is.na(postList))] <- EF[which(is.na(postList))]
  LS[!is.na(LF)] <- LF[!is.na(LF)] - expectedTime[!is.na(LF)]
  while (any(is.na(LF))) {
    for (i in 1:length(activities)) {
      if (!is.na(postList[[i]])) {
        if (!any(is.na(LS[which(is.element(activities, postList[[i]]))]))) {
          LF[i] <- min(LS[which(is.element(activities, postList[[i]]))])
          LS[i] <- LF[i] - expectedTime[i]
        }
      }
    }
  }
  return(list(LS, LF))
}

activities$LS <- calculateLSLF(activities$Activities, postList, activities$`Expected Time`, activities$EF)[[1]]
activities$LF <- calculateLSLF(activities$Activities, postList, activities$`Expected Time`, activities$EF)[[2]]
```

```{r Slack, critical calculation}
# Calculate slack
calculateSlack <- function(L, E) {
  slack <- L - E
  return(slack)
}
activities$Slack <-calculateSlack(activities$LS, activities$ES)

# determine critical
calculateCriticcal <- function(slack) {
  critical <- slack == 0
  return(critical)
}
activities$Critical <- calculateCriticcal(activities$Slack)
```

```{r criticalNodes generation}
# Generate criticalNodes
generateCriticalNodes <- function(activities, critical) {
  criticalNodes <- NA_character_
  for (i in 1:length(activities)) {
    if (critical[i]) {
      criticalNodes <- c(criticalNodes, activities[i])
    }
  }
  criticalNodes <- na.omit(criticalNodes)
  return(criticalNodes)
}

criticalNodes <- generateCriticalNodes(activities$Activities, activities$Critical)
```

```{r Critical path searching}
# Find critical path
findCriticalPath <- function(currentNode, activities_ = activities$Activities, preList_ = preList, startNodes_ = startNodes, criticalNodes_ = criticalNodes){
  if (!is.element(currentNode, criticalNodes_)) {
    return(NA)
  } else if (is.element(currentNode,startNodes_)) {
    return(as.vector(currentNode, mode = "list"))
  } else {
    preTemp <- NA
    for (preNode in preList[[which(activities_ == currentNode)]]) {
      if (is.element(preNode, criticalNodes_)) {
        preTemp <- c(findCriticalPath(preNode, activities_, preList_, startNodes_, criticalNodes_))
      }
    }
    preTemp <- preTemp[which(!is.na(preTemp))]
    if (length(preTemp) == 0) {
      #return(NA)
    } else {
      for (i in 1:length(preTemp)) {
        preTemp[[i]] <- c(preTemp[[i]], currentNode)
      }
      return(preTemp)
    }
  }
}

findCriticalPath(currentNode = "END")
```
